# Generated by Django 3.0 on 2020-03-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
