# Generated by Django 3.0 on 2020-03-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
