# Generated by Django 3.0 on 2020-03-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='pregnant',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
