# Generated by Django 3.0 on 2020-03-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_auto_20200319_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_id', models.CharField(max_length=15)),
                ('symptom_name', models.CharField(max_length=200)),
            ],
        ),
    ]
