# Generated by Django 3.0 on 2020-04-04 13:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='name_of_selected_symptoms',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None), size=None),
        ),
    ]
