# Generated by Django 5.1.5 on 2025-02-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_alter_disease_id_alter_doctor_id_alter_feedback_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.BigIntegerField(),
        ),
    ]
