# Generated by Django 5.1.5 on 2025-02-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_test_testrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
