# Generated by Django 5.1.5 on 2025-02-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0015_alter_test_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='processing_time',
            field=models.IntegerField(blank=True, help_text='Time in hours', null=True),
        ),
    ]
