# Generated by Django 5.1.5 on 2025-02-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0016_alter_test_processing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='request_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='result',
            field=models.FileField(blank=True, null=True, upload_to='test_results/'),
        ),
    ]
