# Generated by Django 5.1.5 on 2025-02-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0017_testrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
